# TXA BACKUP TOOL - Build & Release Engine 2026
# Professional PowerShell Version

$ErrorActionPreference = "Stop"
$AppName = "TXA Backup Tool"
$AppPublisher = "TXA"
$AppContact = "https://fb.com/vlog.txa.2311"
$AppId = "{A75B3CC0-3CAF-4D80-B8E8-0DD4B5E38D1A}"
$ProjectDir = $PSScriptRoot
$ProjectFile = Join-Path $ProjectDir "TXABackupTool.csproj"
$AppVersion = "1.0.0.0"

if (Test-Path $ProjectFile) {
    try {
        [xml]$csproj = Get-Content $ProjectFile
        $version = $csproj.Project.PropertyGroup | ForEach-Object { $_.Version } | Where-Object { $_ }
        if (-not $version) {
            $version = $csproj.Project.PropertyGroup | ForEach-Object { $_.AssemblyVersion } | Where-Object { $_ }
        }
        if (-not $version) {
            $version = $csproj.Project.PropertyGroup | ForEach-Object { $_.FileVersion } | Where-Object { $_ }
        }
        if ($version) {
            $AppVersion = $version.Trim()
        }
    } catch {
        Write-Host "[WARN] Could not read version from csproj. Using default $AppVersion" -ForegroundColor Yellow
    }
}

$PublishPath = Join-Path $ProjectDir "bin\Release\net10.0-windows10.0.19041.0\win-x64\publish"
$IssFile = Join-Path $ProjectDir "Installer.iss"
$SetupOut = "C:\install\Setup"

if (-not (Test-Path $SetupOut)) {
    New-Item -ItemType Directory -Path $SetupOut -Force | Out-Null
}

Clear-Host
Write-Host "========================================================" -ForegroundColor Cyan
Write-Host "         $AppName - BUILD ENGINE 2026" -ForegroundColor Cyan
Write-Host "========================================================" -ForegroundColor Cyan
Write-Host ""

# [1/4] Update Chinese language pack
Write-Host "[1/4] Updating Chinese language pack..." -ForegroundColor Yellow
$LangGenPath = Join-Path $ProjectDir "..\gen_chinese.ps1"
if (Test-Path $LangGenPath) {
    & $LangGenPath
    Write-Host "[OK] Chinese language pack updated." -ForegroundColor Green
} else {
    Write-Host "[WARN] gen_chinese.ps1 not found, skipping." -ForegroundColor Gray
}

# [2/4] Build and Publish application (Multi-file Mode)
Write-Host "`n[2/4] Building and Publishing application..." -ForegroundColor Yellow

# Ensure Publish directory is clean for fresh manifest
if (Test-Path $PublishPath) {
    Remove-Item -Path $PublishPath -Recurse -Force
}

# Standard Publish (Produce many DLLs for faster first-launch and better stability)
dotnet publish (Join-Path $ProjectDir "TXABackupTool.csproj") `
    -c Release `
    --runtime win-x64 `
    --self-contained true `
    -p:PublishSingleFile=false `
    -p:PublishReadyToRun=true `
    -p:DebugType=none `
    -p:DebugSymbols=false `
    -o $PublishPath

if ($LASTEXITCODE -ne 0) {
    Write-Host "`n[ERROR] Build failed! Please check your code." -ForegroundColor Red
    Read-Host "Press Enter to exit..."
    exit $LASTEXITCODE
}

# [Optional] Manually copy folders if not included by MSBuild
$FoldersToCopy = "lang", "Assets"
foreach ($folder in $FoldersToCopy) {
    $src = Join-Path $ProjectDir $folder
    $dst = Join-Path $PublishPath $folder
    if (Test-Path $src) {
        Write-Host "Syncing folder: $folder..." -ForegroundColor Gray
        Copy-Item -Path $src -Destination $PublishPath -Recurse -Force -ErrorAction SilentlyContinue
    }
}
Write-Host "[OK] Build & Resource packaging successful." -ForegroundColor Green

# [3/4] Generating Installer Script (ISS)
Write-Host "`n[3/4] Generating Installer Script (ISS)..." -ForegroundColor Yellow
$IssContent = @"
; TXA BACKUP TOOL - GENERATED BY BUILD ENGINE (MULTI-FILE VERSION)
#define AppName "$AppName"
#define AppVersion "$AppVersion"
#define AppPublisher "$AppPublisher"
#define AppContact "$AppContact"
#define AppId "$AppId"
#define AppExeName "TXABackupTool.exe"
#define FileExt ".txaf"
#define FileExtDesc "TXA Backup Language File"

[Setup]
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppCopyright=© 2026 TXA VLOG — BẢN QUYỀN ĐÃ ĐƯỢC BẢO HỘ
DefaultDirName={localappdata}\Programs\TXABackupTool
DefaultGroupName=TXA Backup Tool
OutputDir=$SetupOut
OutputBaseFilename=TXABackupTool_Setup_v{#AppVersion}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#AppExeName}
SetupIconFile=Assets\logo.ico
DisableWelcomePage=no
DisableDirPage=no
DisableProgramGroupPage=no
DisableReadyPage=no
PrivilegesRequired=lowest
ChangesAssociations=yes
CloseApplications=yes
AppMutex=Global\TXA_BACKUP_TOOL_SINGLE_INSTANCE_2026

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "vietnamese"; MessagesFile: "Vietnamese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Cài đặt toàn bộ nội dung thư mục publish (bao gồm cả thư mục con)
Source: "$PublishPath\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\Liên hệ Tác giả"; Filename: "$AppContact"; IconFilename: "{app}\{#AppExeName}"; IconIndex: 0
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Registry]
Root: HKA; Subkey: "Software\Classes\{#FileExt}"; ValueType: string; ValueName: ""; ValueData: "TXABackupTool.LanguageFile"; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\TXABackupTool.LanguageFile"; ValueType: string; ValueName: ""; ValueData: "{#FileExtDesc}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\TXABackupTool.LanguageFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#AppExeName},0"
Root: HKA; Subkey: "Software\Classes\TXABackupTool.LanguageFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#AppExeName}"" ""%1"""

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// Hàm để lấy chuỗi lệnh gỡ cài đặt từ Registry
function GetUninstallString(): String;
var
  sUninstPath: String;
  sUninstString: String;
begin
  sUninstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#AppId}_is1');
  sUninstString := '';
  if not RegQueryStringValue(HKLM, sUninstPath, 'UninstallString', sUninstString) then
    RegQueryStringValue(HKCU, sUninstPath, 'UninstallString', sUninstString);
  Result := sUninstString;
end;

// Hàm kiểm tra xem đã cài đặt bản cũ chưa
function IsUpgrade(): Boolean;
begin
  Result := (GetUninstallString() <> '');
end;

// Hàm gỡ cài đặt bản cũ một cách im lặng
function UninstallOldVersion(): Integer;
var
  sUninstString: String;
  iResultCode: Integer;
begin
  sUninstString := GetUninstallString();
  if sUninstString <> '' then begin
    sUninstString := RemoveQuotes(sUninstString);
    if Exec(sUninstString, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '', SW_HIDE, ewWaitUntilTerminated, iResultCode) then
      Result := iResultCode
    else
      Result := -1;
  end else
    Result := 0;
end;

function InitializeSetup(): Boolean;
var
  ErrorCode: Integer;
begin
  Result := True;
  // [1] Kill app nếu đang chạy
  ShellExec('open', 'taskkill.exe', '/f /im TXABackupTool.exe /t', '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
  
  // [2] Tự động gỡ cài đặt bản cũ nếu tồn tại
  if IsUpgrade() then begin
    UninstallOldVersion();
  end;
end;

function InitializeUninstall(): Boolean;
var
  ErrorCode: Integer;
begin
  Result := True;
  // Kill app trước khi gỡ
  ShellExec('open', 'taskkill.exe', '/f /im TXABackupTool.exe /t', '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
  Sleep(500); // Đợi 1 chút để process thoát hẳn
end;
"@

Set-Content -Path $IssFile -Value $IssContent -Encoding UTF8
Write-Host "[OK] Installer script generated." -ForegroundColor Green

# [4/4] Checking for Inno Setup and compiling
Write-Host "`n[4/4] Checking for Inno Setup and compiling..." -ForegroundColor Yellow
$Iscc = Get-Command iscc.exe -ErrorAction SilentlyContinue
if ($null -eq $Iscc) {
    Write-Host "[WARN] iscc.exe not found in PATH! Installer .exe cannot be created automatically." -ForegroundColor Gray
    Read-Host "Press Enter to exit..."
    exit 0
}

& $Iscc.Source $IssFile

if ($LASTEXITCODE -ne 0) {
    Write-Host "`n[ERROR] Installer compilation failed!" -ForegroundColor Red
    Read-Host "Press Enter to exit..."
    exit $LASTEXITCODE
}

Write-Host "`n========================================================" -ForegroundColor Cyan
Write-Host "   SUCCESS! Release package is ready." -ForegroundColor Cyan
Write-Host "========================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "[INFO] Installer saved to: $SetupOut\TXABackupTool_Setup.exe" -ForegroundColor White
Write-Host "[TXA VLOG] - 2026" -ForegroundColor White
Write-Host ""
Read-Host "Press Enter to finish..."
