; TXA BACKUP TOOL - GENERATED BY BUILD ENGINE (MULTI-FILE VERSION)
#define AppName "TXA Backup Tool"
#define AppVersion "1.0.0.0"
#define AppPublisher "TXA"
#define AppContact "https://fb.com/vlog.txa.2311"
#define AppId "{A75B3CC0-3CAF-4D80-B8E8-0DD4B5E38D1A}"
#define AppExeName "TXABackupTool.exe"
#define FileExt ".txaf"
#define FileExtDesc "TXA Backup Language File"

[Setup]
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppCopyright=© 2026 TXA VLOG — BẢN QUYỀN ĐÃ ĐƯỢC BẢO HỘ
DefaultDirName={localappdata}\Programs\TXABackupTool
DefaultGroupName=TXA Backup Tool
OutputDir=C:\install\Setup
OutputBaseFilename=TXABackupTool_Setup_v{#AppVersion}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#AppExeName}
SetupIconFile=Assets\logo.ico
DisableWelcomePage=no
DisableDirPage=no
DisableProgramGroupPage=no
DisableReadyPage=no
PrivilegesRequired=lowest
ChangesAssociations=yes
CloseApplications=yes
AppMutex=Global\TXA_BACKUP_TOOL_SINGLE_INSTANCE_2026

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "vietnamese"; MessagesFile: "Vietnamese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Cài đặt toàn bộ nội dung thư mục publish (bao gồm cả thư mục con)
Source: "C:\Users\TXA3100\Desktop\BACKUP - TOOL\TXABackupTool\bin\Release\net10.0-windows10.0.19041.0\win-x64\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\Liên hệ Tác giả"; Filename: "https://fb.com/vlog.txa.2311"; IconFilename: "{app}\{#AppExeName}"; IconIndex: 0
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Registry]
Root: HKA; Subkey: "Software\Classes\{#FileExt}"; ValueType: string; ValueName: ""; ValueData: "TXABackupTool.LanguageFile"; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\TXABackupTool.LanguageFile"; ValueType: string; ValueName: ""; ValueData: "{#FileExtDesc}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\TXABackupTool.LanguageFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#AppExeName},0"
Root: HKA; Subkey: "Software\Classes\TXABackupTool.LanguageFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#AppExeName}"" ""%1"""

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// Hàm để lấy chuỗi lệnh gỡ cài đặt từ Registry
function GetUninstallString(): String;
var
  sUninstPath: String;
  sUninstString: String;
begin
  sUninstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#AppId}_is1');
  sUninstString := '';
  if not RegQueryStringValue(HKLM, sUninstPath, 'UninstallString', sUninstString) then
    RegQueryStringValue(HKCU, sUninstPath, 'UninstallString', sUninstString);
  Result := sUninstString;
end;

// Hàm kiểm tra xem đã cài đặt bản cũ chưa
function IsUpgrade(): Boolean;
begin
  Result := (GetUninstallString() <> '');
end;

// Hàm gỡ cài đặt bản cũ một cách im lặng
function UninstallOldVersion(): Integer;
var
  sUninstString: String;
  iResultCode: Integer;
begin
  sUninstString := GetUninstallString();
  if sUninstString <> '' then begin
    sUninstString := RemoveQuotes(sUninstString);
    if Exec(sUninstString, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '', SW_HIDE, ewWaitUntilTerminated, iResultCode) then
      Result := iResultCode
    else
      Result := -1;
  end else
    Result := 0;
end;

function InitializeSetup(): Boolean;
var
  ErrorCode: Integer;
begin
  Result := True;
  // [1] Kill app nếu đang chạy
  ShellExec('open', 'taskkill.exe', '/f /im TXABackupTool.exe /t', '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
  
  // [2] Tự động gỡ cài đặt bản cũ nếu tồn tại
  if IsUpgrade() then begin
    UninstallOldVersion();
  end;
end;

function InitializeUninstall(): Boolean;
var
  ErrorCode: Integer;
begin
  Result := True;
  // Kill app trước khi gỡ
  ShellExec('open', 'taskkill.exe', '/f /im TXABackupTool.exe /t', '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
  Sleep(500); // Đợi 1 chút để process thoát hẳn
end;
